update

diff --git a/Jenkins b/Jenkins
--- a/Jenkins
+++ b/Jenkins
@@ -383,21 +383,211 @@ pipeline {
                             echo $ENVIRONMENT
 
                             if [ "${SERVICE}" = "ALL" ];then
-                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 api -t ${tagName} || true
-                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 api-internal -t ${tagName} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 api -t ${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 api-internal -t ${JGIT_TAG} || true
 
 
-                            elif [ "${SERVICE}" == "BACKEND" ];then
-                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 api -t ${tagName} || true
-                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 api-internal -t ${tagName} || true
+                            elif [ "${SERVICE}" = "BACKEND" ];then
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 api -t ${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 api-internal -t ${JGIT_TAG} || true
+                            fi
+                            '''
+                        }
+                    }
+                }
+
+                stage('CMS') {
+                    steps {
+                        ws('backend-cms') {
+                            sh 'cp -rf /var/lib/jenkins/jobs/Main\\ pipeline/workspace/* $WORKSPACE'
+
+                            script {
+                                if (SERVICE != 'CMS' && SERVICE != 'ALL') {
+                                    currentBuild.result = 'ABORTED'
+                                    error('Aborting the build.')
+                                }
+                            }
+
+                            // think should work
+                            //step([
+                            //    $class: 'DsbNotificationBuilder',
+                            //    extensions: [
+                            //        [
+                            //            $class: 'ProfileNotifier',
+                            //            message: "${JOB_NAME} - Tag: ${JGIT_TAG} Branch: ${WORK_BRANCH} BuildNum: ${BUILD_NUMBER} - STARTED",
+                            //            name: 'GS Venue DSB'
+                            //        ]
+                            //    ]
+                            //])
+
+                            sh ''' #!/bin/bash
+                            mv src/backend/* ./ && rm -rf src/backend
+                            rm -rf lib/code/source/apps
+                            rm -rf lib/code/source/source_client
+
+                            #Applying custom nginx file
+                            rm nginx_site.conf
+                            mv nginx_site-cms.conf nginx_site.conf
+
+                            mv lib/source2apps lib/code/source/apps
+
+                            mv lib/funimation-source lib/code/source/source_client
+                            cp local_settings.py lib/code/source/source/local_settings.py
+
+                            cp local_settings_client.py lib/code/source/source_client/local_settings.py
+
+                            sed -i "s/.*FROM.*/FROM 933909558080.dkr.ecr.us-west-2.amazonaws.com\\/source2base:latest/" Dockerfile
+                            '''
+
+                            /*sh '''#!/bin/bash
+                            docker build \
+                            -t ${DOCKER_BUILD_MIGRATION}:latest \
+                            -t ${DOCKER_BUILD_MIGRATION}:cms-${JGIT_TAG} \
+                            -f Dockerfile .
+                            #docker push ${ECR_URL}/${APP_NAME}-${APP_ENV_NAME}:latest
+                            #docker push ${ECR_URL}/${APP_NAME}-${APP_ENV_NAME}:cms-${JGIT_TAG}
+                            '''*/
+
+                            // think should work
+                            //step([
+                            //    $class: 'DsbNotificationBuilder',
+                            //    extensions: [
+                            //        [
+                            //            $class: 'ProfileNotifier',
+                            //            message: "${JOB_NAME} - Tag: ${JGIT_TAG} Branch: ${WORK_BRANCH} BuildNum: ${BUILD_NUMBER} - DOCKER IMAGE CREATED\n ${JOB_NAME} - Tag: ${JGIT_TAG} Branch: ${WORK_BRANCH} BuildNum: ${BUILD_NUMBER} - UPDATING AWS.....",
+                            //            name: 'GS Venue DSB'
+                            //        ]
+                            //    ]
+                            //])
+
+                            sh '''#!/bin/bash
+                            if [ $APP_ENV_NAME = "development" ]
+                            then
+                            ENVIRONMENT=DEV
                             fi
 
+                            if [ $APP_ENV_NAME = "qa" ]
+                            then
+                            ENVIRONMENT=QA
+                            fi
 
-                            echo "Wait for the service to reach a stable status"
-                            #aws ecs wait services-stable  --cluster VENUE-${ENVIRONMENT} --services api-internal --region us-west-2 || true
-                            #aws ecs wait services-stable  --cluster VENUE-${ENVIRONMENT} --services api --region us-west-2 || true
-                            #aws ecs wait services-stable  --cluster VENUE-${ENVIRONMENT} --services api-internal --region us-west-2
-                            #aws ecs wait services-stable  --cluster VENUE-${ENVIRONMENT} --services api --region us-west-2
+                            if [ $APP_ENV_NAME = "uat" ]
+                            then
+                            ENVIRONMENT=UAT
+                            fi
+
+                            if [ "${SERVICE}" = "ALL" ];then
+                            #ecs deploy VENUE-${ENVIRONMENT} cms -t cms-${JGIT_TAG} --region us-west-2 || true
+                            #sleep 10
+
+                            elif [ "${SERVICE}" == "CMS" ];then
+                            #ecs deploy VENUE-${ENVIRONMENT} cms -t cms-${JGIT_TAG} --region us-west-2 || true
+                            #sleep 10
+                            fi
+                            '''
+
+                            // think should work
+                            //step([
+                            //    $class: 'DsbNotificationBuilder',
+                            //    extensions: [
+                            //        [
+                            //            $class: 'ProfileNotifier',
+                            //            message: "${JOB_NAME} - Tag: ${JGIT_TAG} Branch: ${WORK_BRANCH} BuildNum: ${BUILD_NUMBER} - AWS TASKS RESTARTED",
+                            //            name: 'GS Venue DSB'
+                            //        ]
+                            //    ]
+                            //])
+                        }
+                    }
+                }
+
+                stage('RqWorkers') {
+                    steps {
+                        ws('backend-rqworkers') {
+                            sh 'cp -rf /var/lib/jenkins/jobs/Main\\ pipeline/workspace/* $WORKSPACE'
+
+                            script {
+                                if (SERVICE != 'RQWORKERS' && SERVICE != 'ALL') {
+                                    currentBuild.result = 'ABORTED'
+                                    error('Aborting the build.')
+                                }
+                            }
+
+                            // think should work
+                            //step([
+                            //    $class: 'DsbNotificationBuilder',
+                            //    extensions: [
+                            //        [
+                            //            $class: 'ProfileNotifier',
+                            //            message: "${JOB_NAME} - Tag: ${JGIT_TAG} Branch: ${WORK_BRANCH} BuildNum: ${BUILD_NUMBER} - STARTED",
+                            //            name: 'GS Venue DSB'
+                            //        ]
+                            //    ]
+                            //])
+
+                            sh ''' #!/bin/bash
+                            mv src/backend/* ./ && rm -rf src/backend
+                            rm -rf lib/code/source/apps
+                            rm -rf lib/code/source/source_client
+
+                            mv lib/source2apps lib/code/source/apps
+                            mv lib/funimation-source lib/code/source/source_client
+
+                            sed -i "s~^DB_REPLICA_HOST.*~DB_REPLICA_HOST = ''~" local_settings.py
+
+                            cp local_settings.py lib/code/source/source/local_settings.py
+                            cp local_settings_client.py lib/code/source/source_client/local_settings.py
+
+                            sed -i "s/.*FROM.*/FROM 933909558080.dkr.ecr.us-west-2.amazonaws.com\\/source2base:latest/" Dockerfile
+                            '''
+
+                            /*sh '''#!/bin/bash
+                            docker build \
+                            -t ${DOCKER_BUILD_MIGRATION}:latest \
+                            -t ${DOCKER_BUILD_MIGRATION}:rqworker-${JGIT_TAG} \
+                            -f Dockerfile .
+                            #docker push ${ECR_URL}/${APP_NAME}-${APP_ENV_NAME}:latest
+                            #docker push ${ECR_URL}/${APP_NAME}-${APP_ENV_NAME}:rqworker-${JGIT_TAG}
+                            '''*/
+
+                            // think should work
+                            //step([
+                            //    $class: 'DsbNotificationBuilder',
+                            //    extensions: [
+                            //        [
+                            //            $class: 'ProfileNotifier',
+                            //            message: "${JOB_NAME} - Tag: ${JGIT_TAG} Branch: ${WORK_BRANCH} BuildNum: ${BUILD_NUMBER} - DOCKER IMAGE CREATED\n ${JOB_NAME} - Tag: ${JGIT_TAG} Branch: ${WORK_BRANCH} BuildNum: ${BUILD_NUMBER} - UPDATING AWS.....",
+                            //            name: 'GS Venue DSB'
+                            //        ]
+                            //    ]
+                            //])
+
+                            sh '''#!/bin/bash
+                            if [ $APP_ENV_NAME = "development" ]
+                            then
+                            ENVIRONMENT=DEV
+                            fi
+
+                            if [ $APP_ENV_NAME = "qa" ]
+                            then
+                            ENVIRONMENT=QA
+                            fi
+
+                            if [ $APP_ENV_NAME = "uat" ]
+                            then
+                            ENVIRONMENT=UAT
+                            fi
+
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 rqworker_default -t rqworker-${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 rqworker_high -t rqworker-${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 rqworker_low -t rqworker-${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 rqworker_low2 -t rqworker-${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 rqworker_normal -t rqworker-${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 rqworker_imports -t rqworker-${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 rqworker_indexing -t rqworker-${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 rqworker_datasync -t rqworker-${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 rqscheduler -t rqworker-${JGIT_TAG} || true
+                            #ecs deploy VENUE-${ENVIRONMENT} --region us-west-2 rqworker -t rqworker-${JGIT_TAG} || true
                             '''
                         }
                     }
